# Generated by Django 3.2.5 on 2021-08-17 11:55

import account.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', image_optimizer.fields.OptimizedImageField(blank=True, default='None.jpg', null=True, upload_to=account.models.upload_image_path, verbose_name='تصویر پروفایل')),
                ('pass_per_save', models.CharField(blank=True, max_length=255, verbose_name='گذر واژه هش نشده')),
                ('gender', models.CharField(blank=True, choices=[('m', 'مرد'), ('w', 'زن'), ('b', 'ترجیح می دهم نگویم')], max_length=1, null=True, verbose_name='جنسیت')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره همراه')),
                ('custom_user_id', models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='کد اختصاصی کاربر')),
                ('code_send', models.IntegerField(blank=True, null=True, verbose_name='کد ارسال شده')),
                ('email_sended', models.BooleanField(default=False, verbose_name='ایمیل ارسال شده است')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
    ]
