# Generated by Django 3.2.5 on 2021-08-17 11:55

from django.db import migrations, models
import home_gallery.models
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, unique=True, verbose_name='موقعیت')),
                ('image', image_optimizer.fields.OptimizedImageField(default='None.jpg', upload_to=home_gallery.models.upload_image_path, verbose_name='انتخاب تصویر')),
                ('status', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری صفحه اصلی',
            },
        ),
    ]
