# Generated by Django 3.2.5 on 2021-08-17 11:55

from django.db import migrations, models
import gallery.models
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دسته')),
                ('status', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='عنوان در نوار آدرس')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, unique=True, verbose_name='موقعیت')),
                ('image', image_optimizer.fields.OptimizedImageField(default='None.jpg', upload_to=gallery.models.upload_image_path, verbose_name='انتخاب تصویر')),
                ('status', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('alt', models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان')),
                ('categories', models.ManyToManyField(related_name='category', to='gallery.Category')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
    ]
