# Generated by Django 3.2.5 on 2021-08-17 11:55

import blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='آدرس مقاله')),
                ('keyword', models.CharField(default='', max_length=255, verbose_name='کلید واژه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('thumbnail', image_optimizer.fields.OptimizedImageField(blank=True, default='None.jpg', upload_to=blog.models.upload_image_path, verbose_name='انتخاب تصویر')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده')], default='d', max_length=1, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='بدون نام', max_length=255, null=True, verbose_name='نام شما')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس ایمیل شما')),
                ('message', models.TextField(verbose_name='پیام شما')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال به میلادی')),
                ('status', models.BooleanField(default=False, verbose_name='نمایش/عدم نمایش')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='برای مقاله ی')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
