# Generated by Django 3.2.5 on 2021-08-17 11:55

from django.db import migrations, models
import image_optimizer.fields
import seo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='وبلاگ', max_length=255, null=True, verbose_name='نام سایت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='درباره سایت')),
                ('status', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
                ('image_logo', image_optimizer.fields.OptimizedImageField(blank=True, default='None.jpg', null=True, upload_to=seo.models.upload_image_path, verbose_name='انتخاب تصویر لوگو')),
                ('owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='مالک سایت')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس کانال')),
                ('telegram_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس کانال_1')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='صفحه ایستا گرام')),
                ('instagram_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='صفحه ایستا گرام_1')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه')),
                ('phone_number_1', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه_1')),
                ('phone_number_2', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه_2')),
                ('phone_number_3', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه_3')),
                ('phone_number_4', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه_4')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('phone_1', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن_1')),
                ('phone_2', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن_2')),
                ('phone_3', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن_3')),
                ('phone_4', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن_4')),
                ('url', models.URLField(blank=True, default='http://example.com', max_length=255, null=True, verbose_name='آدرس دامنه سایت')),
                ('kyword', models.TextField(blank=True, null=True, verbose_name='کلید واژه ها')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('time_work_start', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع کار')),
                ('time_work_end', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان کار')),
                ('addres_google_map', models.TextField(blank=True, null=True, verbose_name='آدرس در گوگل مپ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل')),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل_1')),
            ],
            options={
                'verbose_name': 'سئو',
                'verbose_name_plural': 'سئو',
            },
        ),
    ]
