# Generated by Django 3.2.5 on 2021-08-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='phone_4',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='phone_number_4',
        ),
    ]
